### ISSUE TITLE
Request: Move REPLEX_INCLUDE_WATCHED to Collection Label

### ISSUE THREAD

**Issue by sysmoon14** [lostb1t/replex#47]
Would it be possible to change the include_watched functionality so that it operates at collection level using a label the same way that REPLEXHERO works?

**Comment by luukleenders** [comment]
Any progress on this @lostb1t?

I noticed this feature request and am really interested in seeing it implemented. I've been working on some changes to the `HubMixTransform` and `LibraryMixTransform` that would allow overriding the REPLEX_INCLUDE_WATCHED environment variable with a collection label. I've got a basic implementation working in my local setup.

Since I'm fairly new to Rust, I'd appreciate any feedback or guidance. Would you be open to reviewing a PR for this feature?

**Comment by luukleenders** [comment]
I took a stab at it, details are in the PR, let me know if I did something weird.
